openapi: '3.0.2'
info:
  title: Mobile Customer
  version: '1.0'
servers:
  - url: https://api.server.test/v1
paths:
  /customers:
    get:
      description: Search customers
      responses:
        '200': 
          description: Matching Customers
          $ref: "#/components/responses/CustomerList"
        '400':
          description: Invalid Search criteria
          $ref: "#/components/responses/GenericError"
    post:
      description: Create a new Customer
      responses:
        '201':
          description: Customer Created
          $ref: "#/components/responses/CustomerInfo"
        '400':
          description: Invalid Customer Data
          $ref: "#/components/responses/GenericError"
  /customers/{id}:
    get:
      description: View a Customer
      responses:
        '200':
          description: Customer Details
          $ref: "#/components/responses/CustomerInfo"
        '404':
          description: Customer doesn't exist
          $ref: "#/components/responses/GenericError"
    put:
      description: Update a Customer
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Customer"
      responses:
        '204':
          description: Action Success
        '400':
          description: Update Error
          $ref: "#/components/responses/GenericError"
        '404':
          description: Customer doesn't exist
          $ref: "#/components/responses/GenericError"
    delete:
      description: Delete a Customer
      responses:
        '204':
          description: Action Success
        '404':
          description: Customer doesn't exist
          $ref: "#/components/responses/GenericError"
        '400':
          description: Delete Error
          $ref: "#/components/responses/GenericError"
components:
  schemas:
    Customer:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        surname:
          type: string
        id_card:
          type: string
        address:
          type: string
    MobileSubscriber:
      type: object
      properties:
        id:
          type: integer
        msisdn:
          type: string
        owner:
          type: integer
        user:
          type: integer
        service_type:
          type: string
          enum:
            - MOBILE_PREPAID
            - MOBILE_POSTPAID
        service_start_date:
          type: string
          format: datetime
  responses:
    GenericError:
      description: Generic Error response
      content:
        application/json:
          schema:
            properties:
              message:
                type: string
    CustomerInfo:
      description: Customer Info
      content:        
        application/json:
          schema:
            $ref: "#/components/schemas/Customer"
    CustomerList:
      description: List of Customers
      content:
        application/json:
          schema:
            type: object
            properties:
              customers:
                type: array
                items:
                  $ref: "#/components/schemas/Customer"
              
        
        
        
        